### ISSUE TITLE
Failed to open zip archive '/system/framework/qcom.fmradio.jar': I/O Error

### ISSUE THREAD

**Issue by rubenspessoa** [stone-payments/demo-sdk-android#2]
Pessoal, 

Estou tentando fazer uma transação no SDK de vocês e acredito que seja devido ao seguinte erro: Failed to open zip archive '/system/framework/qcom.fmradio.jar': I/O Error

Segue o log:
```
08-21 15:34:57.572 11855-13269/br.com.stonesdk.sdkdemo W/SSLCertificateSocketFactory: Bypassing SSL security checks at caller's request
08-21 15:34:59.012 11855-13269/br.com.stonesdk.sdkdemo W/art: Failed to open zip archive '/system/framework/qcom.fmradio.jar': I/O Error
                                                              
                                                              [ 08-21 15:34:59.012 11855:13269 W/         ]
                                                              Unable to open '/system/framework/qcom.fmradio.jar': No such file or directory
08-21 15:34:59.012 11855-13269/br.com.stonesdk.sdkdemo W/art: Failed to open zip archive '/system/framework/qcom.fmradio.jar': I/O Error
08-21 15:34:59.252 11855-13269/br.com.stonesdk.sdkdemo W/System.err: java.lang.Exception: Transaction rejected
08-21 15:34:59.252 11855-13269/br.com.stonesdk.sdkdemo W/System.err:     at stone.providers.TransactionProvider.doInBackground(TransactionProvider.java:239)
08-21 15:34:59.252 11855-13269/br.com.stonesdk.sdkdemo W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
08-21 15:34:59.252 11855-13269/br.com.stonesdk.sdkdemo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-21 15:34:59.252 11855-13269/br.com.stonesdk.sdkdemo W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
08-21 15:34:59.252 11855-13269/br.com.stonesdk.sdkdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-21 15:34:59.252 11855-13269/br.com.stonesdk.sdkdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-21 15:34:59.252 11855-13269/br.com.stonesdk.sdkdemo W/System.err:     at java.lang.Thread.run(Thread.java:818)
08-21 15:34:59.262 11855-13801/br.com.stonesdk.sdkdemo E/logger: ====================================================================
                                                                 
                                                                 Nome: xxxxxx
                                                                 SAK: xxxxxx
                                                                 Modelo: xxxxxx
                                                                 Versao do android: xxxxxx
                                                                 Endereco: xxxxxx
                                                                 ====================================================================
08-21 15:34:59.272 11855-11855/br.com.stonesdk.sdkdemo D/ViewRootImpl: #3 mView = null
08-21 15:34:59.302 11855-11855/br.com.stonesdk.sdkdemo E/ViewRootImpl: sendUserActionEvent() mView == null
08-21 15:34:59.302 11855-11855/br.com.stonesdk.sdkdemo D/ViewRootImpl: #1 mView = android.widget.LinearLayout{12895b7 V.E...... ......I. 0,0-0,0 #10203a4 android:id/toast_layout_root}
08-21 15:34:59.332 11855-11855/br.com.stonesdk.sdkdemo D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
08-21 15:35:01.302 11855-11855/br.com.stonesdk.sdkdemo D/ViewRootImpl: #3 mView = null
08-21 15:35:30.022 11855-11855/br.com.stonesdk.sdkdemo V/ActivityThread: updateVisibility : ActivityRecord{35f948d token=android.os.BinderProxy@2b48856 {br.com.stonesdk.sdkdemo/br.com.stonesdk.sdkdemo.activities.TransactionActivity}} show : true
08-21 15:35:48.772 11855-11855/br.com.stonesdk.sdkdemo I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@2b48856 time:127995813
08-21 15:35:52.252 11855-11855/br.com.stonesdk.sdkdemo D/ViewRootImpl: ViewPostImeInputStage processPointer 0
08-21 15:35:52.322 11855-11855/br.com.stonesdk.sdkdemo D/ViewRootImpl: ViewPostImeInputStage processPointer 1
08-21 15:35:52.632 11855-11855/br.com.stonesdk.sdkdemo D/ViewRootImpl: ViewPostImeInputStage processPointer 0
08-21 15:35:52.682 11855-11855/br.com.stonesdk.sdkdemo D/ViewRootImpl: ViewPostImeInputStage processPointer 1
08-21 15:35:52.722 11855-11855/br.com.stonesdk.sdkdemo D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{2e1fa43 V.E...... R.....I. 0,0-0,0}
08-21 15:35:52.732 11855-15314/br.com.stonesdk.sdkdemo D/TRANSACTION_STATUS: TRANSACTION_WAITING_CARD
08-21 15:35:52.772 11855-11855/br.com.stonesdk.sdkdemo D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
08-21 15:35:56.872 11855-15314/br.com.stonesdk.sdkdemo D/TRANSACTION_STATUS: TRANSACTION_WAITING_PASSWORD
08-21 15:36:14.972 11855-15314/br.com.stonesdk.sdkdemo W/art: Failed to open zip archive '/system/framework/qcom.fmradio.jar': I/O Error
                                                              
                                                              [ 08-21 15:36:14.972 11855:15314 W/         ]
                                                              Unable to open '/system/framework/qcom.fmradio.jar': No such file or directory
08-21 15:36:14.972 11855-15314/br.com.stonesdk.sdkdemo W/art: Failed to open zip archive '/system/framework/qcom.fmradio.jar': I/O Error
                                                              
                                                              [ 08-21 15:36:15.312 11855:15314 W/         ]
                                                              Unable to open '/system/framework/qcom.fmradio.jar': No such file or directory
08-21 15:36:15.312 11855-15314/br.com.stonesdk.sdkdemo W/art: Failed to open zip archive '/system/framework/qcom.fmradio.jar': I/O Error
                                                              
                                                              [ 08-21 15:36:15.322 11855:15314 W/         ]
                                                              Unable to open '/system/framework/qcom.fmradio.jar': No such file or directory
08-21 15:36:15.322 11855-15314/br.com.stonesdk.sdkdemo W/art: Failed to open zip archive '/system/framework/qcom.fmradio.jar': I/O Error
08-21 15:36:15.542 11855-15314/br.com.stonesdk.sdkdemo D/TRANSACTION_STATUS: TRANSACTION_SENDING
                                                                             
                                                                             [ 08-21 15:36:15.552 11855:15314 W/         ]
                                                                             Unable to open '/system/framework/qcom.fmradio.jar': No such file or directory
08-21 15:36:15.552 11855-15314/br.com.stonesdk.sdkdemo W/art: Failed to open zip archive '/system/framework/qcom.fmradio.jar': I/O Error
                                                              
                                                              [ 08-21 15:36:15.552 11855:15314 W/         ]
                                                              Unable to open '/system/framework/qcom.fmradio.jar': No such file or directory
08-21 15:36:15.552 11855-15314/br.com.stonesdk.sdkdemo W/art: Failed to open zip archive '/system/framework/qcom.fmradio.jar': I/O Error
08-21 15:36:15.782 11855-15314/br.com.stonesdk.sdkdemo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-21 15:36:15.782 11855-15314/br.com.stonesdk.sdkdemo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-21 15:36:16.162 11855-15314/br.com.stonesdk.sdkdemo W/SSLCertificateSocketFactory: Bypassing SSL security checks at caller's request
08-21 15:36:17.842 11855-15314/br.com.stonesdk.sdkdemo W/art: Failed to open zip archive '/system/framework/qcom.fmradio.jar': I/O Error
                                                              
                                                              [ 08-21 15:36:17.852 11855:15314 W/         ]
                                                              Unable to open '/system/framework/qcom.fmradio.jar': No such file or directory
08-21 15:36:17.852 11855-15314/br.com.stonesdk.sdkdemo W/art: Failed to open zip archive '/system/framework/qcom.fmradio.jar': I/O Error
08-21 15:36:18.122 11855-15314/br.com.stonesdk.sdkdemo W/System.err: java.lang.Exception: Transaction rejected
08-21 15:36:18.122 11855-15314/br.com.stonesdk.sdkdemo W/System.err:     at stone.providers.TransactionProvider.doInBackground(TransactionProvider.java:239)
08-21 15:36:18.122 11855-15314/br.com.stonesdk.sdkdemo W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
08-21 15:36:18.122 11855-15314/br.com.stonesdk.sdkdemo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-21 15:36:18.122 11855-15314/br.com.stonesdk.sdkdemo W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
08-21 15:36:18.122 11855-15314/br.com.stonesdk.sdkdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-21 15:36:18.122 11855-15314/br.com.stonesdk.sdkdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-21 15:36:18.122 11855-15314/br.com.stonesdk.sdkdemo W/System.err:     at java.lang.Thread.run(Thread.java:818)
08-21 15:36:18.122 11855-16015/br.com.stonesdk.sdkdemo E/logger: ====================================================================
                                                                 
                                                                 Nome: xxxxxx
                                                                 SAK: xxxxxx
                                                                 Modelo: xxxxxx
                                                                 Versao do android: xxxxxx
                                                                 Endereco: xxxxxx
                                                                 ====================================================================
08-21 15:36:18.162 11855-11855/br.com.stonesdk.sdkdemo D/ViewRootImpl: #3 mView = null
08-21 15:36:18.192 11855-11855/br.com.stonesdk.sdkdemo E/ViewRootImpl: sendUserActionEvent() mView == null
08-21 15:36:18.192 11855-11855/br.com.stonesdk.sdkdemo D/ViewRootImpl: #1 mView = android.widget.LinearLayout{e83164d V.E...... ......I. 0,0-0,0 #10203a4 android:id/toast_layout_root}
08-21 15:36:18.242 11855-11855/br.com.stonesdk.sdkdemo D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
08-21 15:36:20.192 11855-11855/br.com.stonesdk.sdkdemo D/ViewRootImpl: #3 mView = null
```

**Comment by filpgame** [comment]
Olá @rubenspessoa 
Creio que este erro não está relacionado à SDK, uma vez que não fazemos referência nenhuma à esse jar: `/system/framework/qcom.fmradio.jar` . Você está testando no ambiente `SANDBOX` ou `PRODUCTION`?
Se for em `PRODUCTION`, troque para `SANDBOX` e nos mande o log dos comandos por favor. As tags dos logs são `COMMAND_REQUEST` e `COMMAND_RESPONSE`
Obrigado!

**Comment by rubenspessoa** [comment]
Olá, @filpgame. Tudo bom? Cara, eu estou usando no ambiente SANDBOX mesmo. O erro aconteceu quando usei o aparelho Samsung J5. Quando mudei para o aparelho Moto G4 não aconteceu e continuei com o desenvolvimento.
