### ISSUE TITLE
Erro Attempt to invoke virtual method

### ISSUE THREAD

**Issue by ViniciusAugusto** [stone-payments/demo-sdk-android#6]
Estou com o seguinte erro abaixo ao rodar o app no POS Android N5.

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: br.com.stonesdk.sdkdemo, PID: 13316
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List stone.application.SessionApplication.getUserModelList()' on a null object reference
        at stone.providers.ActiveApplicationProvider.<init>(ActiveApplicationProvider.java:60)
        at br.com.stonesdk.sdkdemo.activities.ValidationActivity.onClick(ValidationActivity.java:84)
        at android.view.View.performClick(View.java:4781)
        at android.view.View$PerformClick.run(View.java:19892)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
I/Process: Sending signal. PID: 13316 SIG: 9`

Estou realizando o teste da demo na branch **3.2.0-RC3**

**Comment by ViniciusAugusto** [comment]
> Estou com o seguinte erro abaixo ao rodar o app no POS Android N5.
> 
> `E/AndroidRuntime: FATAL EXCEPTION: main Process: br.com.stonesdk.sdkdemo, PID: 13316 java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List stone.application.SessionApplication.getUserModelList()' on a null object reference at stone.providers.ActiveApplicationProvider.<init>(ActiveApplicationProvider.java:60) at br.com.stonesdk.sdkdemo.activities.ValidationActivity.onClick(ValidationActivity.java:84) at android.view.View.performClick(View.java:4781) at android.view.View$PerformClick.run(View.java:19892) at android.os.Handler.handleCallback(Handler.java:739) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:135) at android.app.ActivityThread.main(ActivityThread.java:5254) at java.lang.reflect.Method.invoke(Native Method) at java.lang.reflect.Method.invoke(Method.java:372) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697) I/Process: Sending signal. PID: 13316 SIG: 9`
> 
> Estou realizando o teste da demo na branch **3.2.0-RC3**
